### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by AlexDicy** [HAlexTM/Conebase#1]
- [x] change "small" buttons to "extra small" and "small"
- [x] add rounded buttons
- [ ] add modals/alerts classes (with animations)
- [ ] add notifications classes (with animations)
- [ ] add an animation for the input labels (MD)

Maybe:
- add Material Design icons
